config/routes.rb
Rails.application.routes.draw do
  root 'user_backoffice/tasks#index'

  namespace :user_backoffice do
    resources :tasks
    resources :tasks do
      patch 'complete', on: :member
      patch 'shared', on: :member
      get 'shared_tasks', on: :collection
    end
    resources :list_shareds
    get 'home/index'
  end
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :user_backoffice_tasks, class_name: 'UserBackoffice::Task', dependent: :destroy
  has_many :user_backoffice_list_shareds, class_name: 'UserBackoffice::ListShared', dependent: :destroy
end

app/models/user_backoffice.rb
module UserBackoffice
  def self.table_name_prefix
    "user_backoffice_"
  end
end

app/models/user_backoffice/list_shared.rb
class UserBackoffice::ListShared < ApplicationRecord
  belongs_to :user_backoffice_task, class_name: 'UserBackoffice::Task', foreign_key: 'user_backoffice_task_id'
  belongs_to :user
end

app/models/user_backoffice/task.rb
class UserBackoffice::Task < ApplicationRecord
  belongs_to :user
  has_many :user_backoffice_list_shareds, class_name: 'UserBackoffice::ListShared', dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/layout_user_controller.rb
class LayoutUserController < ApplicationController
    layout 'layout_user'
    before_action :authenticate_user!
end

app/controllers/user_backoffice/home_controller.rb
class UserBackoffice::HomeController < LayoutUserController
  def index
    @user_backoffice_tasks = []

    @historyc = current_user.user_backoffice_tasks.where(status: "Concluída")
    @historyc.each do |task|
      @user_backoffice_tasks.push([task, User.find_by(id: task.user_id)])
    end
    
    @shared_with_user = current_user.user_backoffice_list_shareds
    @shared_with_user.each do |task|
      task = UserBackoffice::Task.find_by(id: task.user_backoffice_task_id)
      if task.status == "Concluída" && !@user_backoffice_tasks.any? { |existing_task, _| existing_task.id == task.id }
        @user_backoffice_tasks.push([task, User.find_by(id: task.user_id)])
      end
    end
  end
    
end

app/controllers/user_backoffice/list_shareds_controller.rb
class UserBackoffice::ListSharedsController < LayoutUserController
  before_action :set_user_backoffice_list_shared, only: %i[ show ]

  # GET /user_backoffice/list_shareds or /user_backoffice/list_shareds.json
  def index
    @user_backoffice_tasks = []
    @shared_with_user = current_user.user_backoffice_list_shareds
    @shared_with_user.each do |description_shared|
      task = UserBackoffice::Task.find_by(id: description_shared.user_backoffice_task_id)
      if task.status == "Não concluída"
        shared_with_task = []
        UserBackoffice::ListShared.where(user_backoffice_task_id: description_shared.user_backoffice_task_id).each do |shared_task|
          shared_with_task.push(User.find_by(id: shared_task.user_id))
        end
        @user_backoffice_tasks.push([task, shared_with_task, User.find_by(id: task.user_id)])
      end
    end
  end

 
  # POST /user_backoffice/list_shareds or /user_backoffice/list_shareds.json
  
  # PATCH/PUT /user_backoffice/list_shareds/1 or /user_backoffice/list_shareds/1.json
  
  # DELETE /user_backoffice/list_shareds/1 or /user_backoffice/list_shareds/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_backoffice_list_shared
      @user_backoffice_list_shared = UserBackoffice::ListShared.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_backoffice_list_shared_params
      params.require(:user_backoffice_list_shared).permit(:task_id, :user_id)
    end
end

app/controllers/user_backoffice/tasks_controller.rb
class UserBackoffice::TasksController < LayoutUserController
  before_action :set_user_backoffice_task, only: %i[ show edit update destroy]

  # GET /user_backoffice/tasks or /user_backoffice/tasks.json
  def index
    @user_backoffice_tasks = current_user.user_backoffice_tasks.where(shared: 0, status: "Não concluída")


    @user_backoffice_shared_tasks = current_user.user_backoffice_tasks.where(shared: 1,status: "Não concluída" )
    @shared_with_user = []

    @user_backoffice_shared_tasks.each do |task|
      shared_with_task = []
      UserBackoffice::ListShared.where(user_backoffice_task_id: task.id).each do |shared_task|
        shared_with_task.push(User.find_by(id: shared_task.user_id))
      end
      @shared_with_user.push([task, shared_with_task, User.find_by(id: task.user_id)])
      puts "++++++++++++++++++++++++++++++++++"
      puts task.inspect
    end
    
  end

  def complete
    
    @user_backoffice_task = UserBackoffice::Task.find(params[:id])
    
    @user_backoffice_task.update(status: "Concluída")
    redirect_to root_path, notice: "Tarefa concluida!"
  end

  def shared
    user = User.find_by(email: params[:email])
    if user
      @user_backoffice_task = UserBackoffice::Task.find_by(id: params[:id])
      if @user_backoffice_task.nil?
        redirect_to root_path, alert: "Tarefa não encontrada!"
        return
      end

      UserBackoffice::ListShared.create(
        user_backoffice_task_id: @user_backoffice_task.id,
        user_id: user.id
      )
      
      @user_backoffice_task.update(shared: 1)

      redirect_to root_path, notice: "Tarefa compartilhada com sucesso!"
    else
      redirect_to root_path, alert: "Usuário não encontrado!"
    end
  end

  # GET /user_backoffice/tasks/1 or /user_backoffice/tasks/1.json
  def show
  end

  # GET /user_backoffice/tasks/new
  def new
    @user_backoffice_task = UserBackoffice::Task.new
  end

  # GET /user_backoffice/tasks/1/edit
  def edit
  end

  # POST /user_backoffice/tasks or /user_backoffice/tasks.json
  def create
    task = user_backoffice_task_params
    task[:status] = params[:status]
    task[:user_id] = params[:user_id]

    @user_backoffice_task = UserBackoffice::Task.new(task)

    respond_to do |format|
      if @user_backoffice_task.save
        format.html { redirect_to user_backoffice_task_url(@user_backoffice_task), notice: "Tarefa criada com sucesso" }
        format.json { render :show, status: :created, location: @user_backoffice_task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_backoffice_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_backoffice/tasks/1 or /user_backoffice/tasks/1.json
  def update
    respond_to do |format|
      if @user_backoffice_task.update(user_backoffice_task_params)
        format.html { redirect_to user_backoffice_task_url(@user_backoffice_task), notice: "Tarefa editada com sucesso" }
        format.json { render :show, status: :ok, location: @user_backoffice_task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_backoffice_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_backoffice/tasks/1 or /user_backoffice/tasks/1.json
  def destroy
    @user_backoffice_task.destroy!

    respond_to do |format|
      format.html { redirect_to user_backoffice_tasks_url, notice: "Tarefa excluida com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_backoffice_task
      @user_backoffice_task = UserBackoffice::Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_backoffice_task_params
      params.require(:user_backoffice_task).permit(:title, :description, :status, :priority, :shared, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_backoffice/home_helper.rb
module UserBackoffice::HomeHelper
end

app/helpers/user_backoffice/list_shareds_helper.rb
module UserBackoffice::ListSharedsHelper
end

app/helpers/user_backoffice/tasks_helper.rb
module UserBackoffice::TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciador de Tarefas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@^2.2/dist/tailwind.min.css" rel="stylesheet">

    <%= javascript_importmap_tags %>
  </head>

  <body class=" h-screen w-screen">
    <main class="container mx-auto px-5 flex ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/layout_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciador de Tarefas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@^2.2/dist/tailwind.min.css" rel="stylesheet">

    <%= javascript_importmap_tags %>
  </head>

  <body class=" h-screen w-screen">
    <%= render "components/sidebar" %>
    <main class="container mx-auto px-5 flex ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/user_backoffice/home/index.html.erb
<div class="w-full">
  <% content_for :title, "List shareds" %>

  <div class="flex justify-between items-center mt-2">
    <h1 class="font-bold text-2xl mr-auto ml-0 font-sans text-gray-700">Tarefas concluídas</h1>
  </div>
  <% if notice.present? %>                  
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

  <div id="user_backoffice_tasks" class="grid grid-cols-2 gap-4 mt-8">
  <% if @user_backoffice_tasks.empty?%>
    <p>Você não possui nenhuma tarefa concluída</p>
  <% end %>
      <% @user_backoffice_tasks.each do |user_backoffice_task| %>
          <div class="flex flex-col pb-2 border border-gray-200 rounded-md mb-2">
              
              <div class="w-full justify-center text-white p-2 flex px-4 bg-purple-600 rounded-t-md">
                  <h4><%= user_backoffice_task[0].title %></h4>
                  <%= button_tag type: 'button', class: "button_description text-white mr-0 ml-auto" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down">
                      <path d="m6 9 6 6 6-6"/>
                      </svg>
                  <% end %>
              </div>

              <div  class="description_section mt-4 p-4  border-b border-gray-400 hidden text-gray-500 text-sm">
                  <p class="font-semibold">Descrição da tarefa:</p>
                  <p class="border-b border-gray-400 mb-2 py-2"><%= user_backoffice_task[0].description %></p>
                  
                  <p class="font-semibold mt-2">Criador da tarefa:</p>
                  <p class="py-2"><%= user_backoffice_task[1].email %></p>

              </div>
              <p class="m-2 px-2 text-center items-center text-white bg-green-500 rounded-lg ">Tarefa concluída!</p>
              <p class="m-2 px-2 text-center items-center text-gray-600">Concluída em: <%= user_backoffice_task[0].updated_at.strftime("%d/%m/%Y") %></p>
                      
          </div>
          <!-- Main modal -->
          <div id="shared_<%=user_backoffice_task[0].id%>" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
              <div class="relative p-4 w-full max-w-md max-h-full">
                  <!-- Modal content -->
                  <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                      <!-- Modal header -->
                      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                          <h3 class="text-base font-semibold text-gray-900 dark:text-white">
                              Compartilhar tarefa: <%= user_backoffice_task[0].title %>
                          </h3>
                          <button type="button" class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center " data-modal-hide="shared_<%=user_backoffice_task[0].id%>">
                              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                              </svg>
                          </button>
                      </div>
                      <!-- Modal body -->
                      <div class="p-4 md:p-5">
                          <%= form_with(url: shared_user_backoffice_task_path(user_backoffice_task[0]), method: :patch, local: true) do |form| %>
                              <div>
                                  <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Adicionar email de participante</label>
                                  <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>    
                              </div>
                              <%= button_tag type: 'submit', class: "w-full mt-2 text-white bg-purple-600 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" do %>
                                  Compartilhar
                              <% end %>
                          <% end %>
                      </div>
                  </div>
              </div>
          </div>
      <% end %>
  </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  var toggleButtons = document.querySelectorAll(".button_description");
  var toggleDivs = document.querySelectorAll(".description_section");

  toggleButtons.forEach(function(button, index) {
    button.addEventListener("click", function() {
      toggleDivs[index].classList.toggle("hidden");
    });
  });
});
</script>

app/views/user_backoffice/list_shareds/index.html.erb
<div class="w-full">
    <% content_for :title, "List shareds" %>

    <div class="flex justify-between items-center mt-2">
      <h1 class="font-bold text-2xl mr-auto ml-0 font-sans text-gray-700">Tarefas Compartilhadas comigo</h1>
    </div>
    <% if notice.present? %>                  
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>


    <div id="user_backoffice_tasks" class="grid grid-cols-2 gap-4 mt-8">
		<% if @user_backoffice_tasks.empty?%>
			<p>Quando compartilharem tarefas com você, elas aparecerão aqui</p>
		<% end %>
        <% @user_backoffice_tasks.each do |user_backoffice_task| %>
            <div class="flex flex-col pb-2 border border-gray-200 rounded-md mb-2">
                
                <div class="w-full justify-center text-white p-2 flex px-4 bg-purple-600 rounded-t-md">
                    <h4><%= user_backoffice_task[0].title %></h4>
                    <%= button_tag type: 'button', class: "button_description text-white mr-0 ml-auto" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down">
                        <path d="m6 9 6 6 6-6"/>
                        </svg>
                    <% end %>
                </div>

                <div  class="description_section mt-4 p-4  border-b border-gray-400 hidden text-gray-500 text-sm">
                    <p class="font-semibold">Descrição da tarefa:</p>
                    <p class="border-b border-gray-400 mb-2 py-2"><%= user_backoffice_task[0].description %></p>
                    
                    <p class="font-semibold mt-2">Criador da tarefa:</p>
                    <p class="border-b border-gray-400 mb-2 py-2"><%= user_backoffice_task[2].email %></p>

                    <p class="font-semibold mt-2">Pessoas com acesso a essa tarefa:</p>
                    <% user_backoffice_task[1].each do |user_shared| %>
                        <p class=" py-2"><%= user_shared.email %></p>
                    <% end %>
                </div>
                <p class="p-2 items-center text-gray-300">Tarefa não concluída, criada em: <%= user_backoffice_task[0].created_at.strftime("%d/%m/%Y")%> </p>
                <div class="p-2 grid grid-cols-3 w-full">
        
                    <p class="text-white rounded-lg p-1 text-center  text-sm w-full items-center <%= case user_backoffice_task[0].priority
                    when 'Alta'
                        'bg-red-500'
                    when 'Baixa'
                        'bg-blue-600' 
                    else
                        'bg-yellow-600'
                    end %>">
                        Prioridade <%= user_backoffice_task[0].priority %>
                    </p>
                    <p></p>
                    <%= form_with(url: complete_user_backoffice_task_path(user_backoffice_task[0]), method: :patch, local: true) do |form| %>
                        <%= button_tag type: 'submit', class: "text-white rounded-lg p-1 text-center text-sm bg-green-400 flex px-2  w-full" do %>
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check mr-2">
                            <path d="M20 6 9 17l-5-5"/>
                            </svg>
                            Concluir
                        <% end %>
                    <% end %>                   
                </div>
                        
            </div>
            <!-- Main modal -->
            <div id="shared_<%=user_backoffice_task[0].id%>" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                    <!-- Modal content -->
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <!-- Modal header -->
                        <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                            <h3 class="text-base font-semibold text-gray-900 dark:text-white">
                                Compartilhar tarefa: <%= user_backoffice_task[0].title %>
                            </h3>
                            <button type="button" class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center " data-modal-hide="shared_<%=user_backoffice_task[0].id%>">
                                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                </svg>
                            </button>
                        </div>
                        <!-- Modal body -->
                        <div class="p-4 md:p-5">
                            <%= form_with(url: shared_user_backoffice_task_path(user_backoffice_task[0]), method: :patch, local: true) do |form| %>
                                <div>
                                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Adicionar email de participante</label>
                                    <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>    
                                </div>
                                <%= button_tag type: 'submit', class: "w-full mt-2 text-white bg-purple-600 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" do %>
                                    Compartilhar
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var toggleButtons = document.querySelectorAll(".button_description");
    var toggleDivs = document.querySelectorAll(".description_section");

    toggleButtons.forEach(function(button, index) {
      button.addEventListener("click", function() {
        toggleDivs[index].classList.toggle("hidden");
      });
    });
  });
</script>

app/views/user_backoffice/tasks/_form.html.erb
<%= form_with(model: user_backoffice_task, class: "contents") do |form| %>
  <% if user_backoffice_task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user_backoffice_task.errors.count, "error") %> prohibited this user_backoffice_task from being saved:</h2>

      <ul>
        <% user_backoffice_task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-2">
    <%= form.label :title, "Título" ,class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white"%>
    <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5" %>
  </div>

  <div class="my-2">
    <%= form.label :description, "Descrição" , class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_area :description, rows: 4, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5" %>
  </div>
  <div class="my-2">
    <%= form.label :priority , "Prioridade", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white"%>
    <%= form.select :priority, options_for_select([['Alta', 'Alta'], ['Média', 'Média'], ['Baixa', 'Baixa']]),{}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5" %>
  </div>

  <div class="flex my-8">
    <%= form.check_box :shared,  class: "w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800" %>
    <%= form.label :shared, "Compartilhar tarefa", class:"ml-2 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
  </div>
 
  <%= hidden_field_tag :status, 'Não concluída' %>
  <%= hidden_field_tag :user_id, current_user.id %>

  <div class="inline">
    <%= form.submit "Confirmar" ,class: "bg-purple-600 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_backoffice/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <div class="w-full justify-center text-white rounded-lg p-2 flex px-4 bg-purple-600">
    <%= task.title %>
  </div>

  <div class="my-5">
    <strong class="block text-sm font-medium text-gray-900 my-1">Descrição da tarefa</strong>
    <p class = "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg w-full p-2.5"><%= task.description %></p>
  </div>

  <div class="my-5">
    <strong class="block text-sm font-medium text-gray-900 my-1">Andamento</strong>
    <p class = "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg w-full p-2.5"><%= task.status %></p>
  </div>

  <div class="my-5">
    <strong class="block text-sm font-medium text-gray-900 my-1">Prioridade</strong>
    <p class = "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg w-full p-2.5"><%= task.priority %></p>
  </div>
  
  <div class="my-5">
    <strong class="block text-sm font-medium text-gray-900 my-1">Compartilhamento</strong>
    <p class = "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg w-full p-2.5"><%= case task.shared
      when 1
        'Tarefa compartilhada'
      
      else
        'Tarefa não compartilhada'
      end %>
    </p>
  </div>

</div>

app/views/user_backoffice/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editar tarefa</h1>

  <%= render "form", user_backoffice_task: @user_backoffice_task %>

  <%= link_to "Voltar", user_backoffice_tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_backoffice/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova tarefa</h1>

  <%= render "form", user_backoffice_task: @user_backoffice_task %>

  <%= link_to "Voltar", user_backoffice_tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_backoffice/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user_backoffice_task %>

    <div class="grid grid-cols-3 gap-4">
      <%= link_to "Editar tarefa", edit_user_backoffice_task_path(@user_backoffice_task), class: "text-center mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium w-full" %>
      <%= link_to "Voltar", user_backoffice_tasks_path, class: "text-center mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium w-full"  %>
      <%= button_to "Excluir tarefa", @user_backoffice_task, method: :delete, class: "text-center mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium w-full"  %>
  </div>
  </div>
</div>